[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-vcs", "hatchling" ]

[project]
name = "evd-convert"
description = "Add your description here"
readme = "README.md"
authors = [
  { name = "Gavin Macaulay" },
]
requires-python = ">=3.14"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Oceanography",
  "Topic :: Scientific/Engineering :: Physics",
]
dynamic = [ "version" ]
dependencies = [
  "xmltodict>=1.0.4",
]
scripts.evdconvert = "evd_convert.main:main"

[dependency-groups]
dev = [
  "prek>=0.5.3",
  "zensical>=0.0.59",
]

[tool.hatch]
version.source = "vcs"
version.raw-options.local_scheme = "no-local-version"  # otherwise the non-tagged version is not accepted by testpypi
build.targets.wheel.packages = [ "src/evd_convert" ]

[tool.uv]
exclude-newer = "7 days"

[tool.ruff]
line-length = 100
preview = true
lint.extend-select = [
  "B006", # do not use mutable structures for argument defaults
  "C4",   # Catch incorrect use of comprehensions, dict, list, etc
  "FA",   # Enforce from __future__ import annotations
  "FURB", # Suggest more idiomatic Python patterns
  "I",    # Sort imports properly
  "ICN",  # Use common import conventions
  "ISC",  # Good use of string concatenation
  "NPY",  # Some numpy-specific things
  "PTH",  # Use pathlib instead of os.path
  "RET",  # Good return practices
  "SIM",  # Common simplification rules
  "TC",   # Enforce importing certain types in a TYPE_CHECKING block
  "TD",   # Be diligent with TODO comments
  "TID",  # Some good import practices
  "UP",   # Warn if certain things can changed due to newer Python versions
  "W",    # PyCodeStyle warnings
]
lint.ignore = [
  "missing-todo-author",
  "missing-todo-link",
]
